apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      containers:
      - name: example
        image: busybox
        command: [ "sleep", "10" ]
      restartPolicy: Never
