---
# file: practice/2.application-abstractions/2.replicaset/replicaset.yaml
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: debian:jessie
        command: ['sh', '-c', 'while true; do echo "Hello, ${USERNAME}!"; sleep 2; done']
        name: hello
        ports:
        - containerPort: 80
        env:
        - name: USERNAME
          value: myname
...
